name: Notify merge on Google Chat 

on:
  push:
    branches:
      - main

jobs:
  notify_pull_request_google_chat:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Google Chat
        if: ${{ always() }} # Use always to ensure that the notification is also send on failure of former steps
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: 'https://chat.googleapis.com/v1/spaces/AAAAFRzZf0Y/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=6rGh5ODVeRx6pZ96DBVdx4-gf3QSncWsYS4AH3qvra8'
          title: Nouvelle mise à jour sur Thotify !
          subtitle: Merge request successfully 😻