name: Notify pull request on Google Chat 

on:
  pull_request:
    branches:
      - main

jobs:
  notify_pull_request_google_chat:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Google Chat
        if: ${{ always() }} # Use always to ensure that the notification is also send on failure of former steps
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: 'https://chat.googleapis.com/v1/spaces/AAAAMZVoXW0/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=clmUzAUa9ixKAFvHMDSxe5w6pt8nEio1e9EqVGLN19E'
          title: Un pull request sur Thotify !
          subtitle: Hey Admins! You have to merge a new Pull Request  ! 🪄